
name: Docs to PDF
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'crsf.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: 'crsf.md'
          output_dir: 'export'
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: crsf.pdf
          path: export
          if-no-files-found: warn
